// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ehJVrFPkH4uBWMg7rfIVtpWn4REISoI',
    appId: '1:423467755843:web:ab1649a4f3f29ae68d67f6',
    messagingSenderId: '423467755843',
    projectId: 'cafe-pos-system-251f5',
    authDomain: 'cafe-pos-system-251f5.firebaseapp.com',
    storageBucket: 'cafe-pos-system-251f5.firebasestorage.app',
    measurementId: 'G-CDCJSE8DJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvkuOL8PqZTKYNcEpsTnai7ToA1smftrw',
    appId: '1:423467755843:android:f264b25e0379349d8d67f6',
    messagingSenderId: '423467755843',
    projectId: 'cafe-pos-system-251f5',
    storageBucket: 'cafe-pos-system-251f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEVF8G9K-_kbxEm4uq8rNz5Pi-MxMOcH0',
    appId: '1:423467755843:ios:1bfa5d384677a4b08d67f6',
    messagingSenderId: '423467755843',
    projectId: 'cafe-pos-system-251f5',
    storageBucket: 'cafe-pos-system-251f5.firebasestorage.app',
    iosBundleId: 'com.example.cafePosSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEVF8G9K-_kbxEm4uq8rNz5Pi-MxMOcH0',
    appId: '1:423467755843:ios:1bfa5d384677a4b08d67f6',
    messagingSenderId: '423467755843',
    projectId: 'cafe-pos-system-251f5',
    storageBucket: 'cafe-pos-system-251f5.firebasestorage.app',
    iosBundleId: 'com.example.cafePosSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ehJVrFPkH4uBWMg7rfIVtpWn4REISoI',
    appId: '1:423467755843:web:5feaf2586a1200ad8d67f6',
    messagingSenderId: '423467755843',
    projectId: 'cafe-pos-system-251f5',
    authDomain: 'cafe-pos-system-251f5.firebaseapp.com',
    storageBucket: 'cafe-pos-system-251f5.firebasestorage.app',
    measurementId: 'G-203MMXVM7Z',
  );
}
